openapi: 3.0.0
info:
  title: Job Board API
  version: 1.0.0
  description: RESTful API for a job board with Admin and User roles.

servers:
  - url: http://localhost:5000

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Job:
      type: object
      properties:
        title:
          type: string
        company:
          type: string
        description:
          type: string
        location:
          type: string
        type:
          type: string
          enum: [Full-time, Part-time, Contract]
        salary:
          type: string
        deadline:
          type: string
          format: date
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        resume:
          type: string
        profilePic:
          type: string
        skills:
          type: array
          items:
            type: string

security:
  - BearerAuth: []

paths:
  /api/admin/signup:
    post:
      summary: Register an admin
      tags: [Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: Admin created
  /api/admin/login:
    post:
      summary: Admin login
      tags: [Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Logged in
  /api/user/signup:
    post:
      summary: Register a user
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: User created
  /api/user/login:
    post:
      summary: User login
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Logged in
